# Generated by Django 4.2.24 on 2025-10-06 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("open", "Open"),
                            ("click", "Click"),
                            ("bounce", "Bounce"),
                            ("unsubscribe", "Unsubscribe"),
                            ("spam_report", "Spam Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="contacts.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "indexes": [
                    models.Index(
                        fields=["organization", "event_type"],
                        name="analytics_e_organiz_21eb36_idx",
                    ),
                    models.Index(
                        fields=["campaign", "event_type"],
                        name="analytics_e_campaig_05286a_idx",
                    ),
                    models.Index(
                        fields=["contact"], name="analytics_e_contact_635569_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="analytics_e_event_t_7fd62a_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="analytics_e_created_c06122_idx"
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="analytics_e_organiz_97c55f_idx",
                    ),
                ],
            },
        ),
    ]
