# Generated by Django 4.2.24 on 2025-10-06 12:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0001_initial"),
        ("accounts", "0001_initial"),
        ("contacts", "0001_initial"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "from_email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("from_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("html_content", models.TextField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                ("total_bounced", models.IntegerField(default=0)),
                ("total_unsubscribed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="contacts.contactgroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="domains.domain",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="accounts.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="templates.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_recipients",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_recipients",
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="campaign_re_campaig_6c3c85_idx",
                    ),
                    models.Index(
                        fields=["contact"], name="campaign_re_contact_0f43bc_idx"
                    ),
                    models.Index(
                        fields=["status"], name="campaign_re_status_f95b2a_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="campaign_re_sent_at_2732e3_idx"
                    ),
                    models.Index(
                        fields=["opened_at"], name="campaign_re_opened__1321d6_idx"
                    ),
                    models.Index(
                        fields=["clicked_at"], name="campaign_re_clicked_e49ba6_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="campaign_re_created_783ad2_idx"
                    ),
                ],
                "unique_together": {("campaign", "contact")},
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "status"], name="campaigns_organiz_0c0cd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="campaigns_status_a03570_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["scheduled_at"], name="campaigns_schedul_e9d492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["sent_at"], name="campaigns_sent_at_645c14_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["created_by"], name="campaigns_created_b46a1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="campaigns_organiz_f41a9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["-created_at"], name="campaigns_created_163163_idx"
            ),
        ),
    ]
