# Generated by Django 4.2.24 on 2025-10-06 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionNotification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("trial_ending", "Trial Ending"),
                            ("trial_ended", "Trial Ended"),
                            ("subscription_renewed", "Subscription Renewed"),
                            ("subscription_canceled", "Subscription Canceled"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_succeeded", "Payment Succeeded"),
                            ("limit_warning", "Limit Warning"),
                            ("limit_reached", "Limit Reached"),
                            ("team_invitation_received", "Team Invitation Received"),
                            ("team_invitation_accepted", "Team Invitation Accepted"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-App"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("delivery_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_notifications",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "notification_type", "-created_at"],
                        name="subscriptio_organiz_e0c7a2_idx",
                    ),
                    models.Index(
                        fields=["status", "channel"],
                        name="subscriptio_status_f96653_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="subscriptio_user_id_2956df_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_read"],
                        name="subscriptio_organiz_4e1835_idx",
                    ),
                ],
            },
        ),
    ]
