# Generated by Django 4.2.24 on 2025-10-06 12:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "sid",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("sess", models.JSONField()),
                ("expire", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
            ],
            options={
                "db_table": "email_otps",
                "indexes": [
                    models.Index(
                        fields=["email", "is_verified"],
                        name="email_otps_email_f84f45_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="email_otps_expires_040e75_idx"
                    ),
                ],
            },
        ),
    ]
