# Generated by Django 4.2.25 on 2025-10-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_replit__fd5f2c_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="replit_id",
        ),
    ]
