# Generated by Django 4.2.24 on 2025-10-06 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("html_content", models.TextField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="email_templ_organiz_0de6eb_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="email_templ_is_defa_fb5e77_idx"
                    ),
                    models.Index(
                        fields=["category"], name="email_templ_categor_e84d9c_idx"
                    ),
                    models.Index(
                        fields=["organization", "is_default"],
                        name="email_templ_organiz_cda13f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="email_templ_created_9d4e95_idx"
                    ),
                ],
            },
        ),
    ]
