global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'engagex-production'
    environment: 'production'

rule_files:
  - '/etc/prometheus/alerts/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['django:8001']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'django_.*'
        action: keep

  - job_name: 'express-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['express:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'email-delivery'
    metrics_path: '/api/metrics/sendgrid'
    static_configs:
      - targets: ['django:8001']
    scrape_interval: 60s
