# Generated by Django 4.2.24 on 2025-10-06 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dkim_record", models.TextField(blank=True, null=True)),
                ("cname_record", models.TextField(blank=True, null=True)),
                ("dmarc_record", models.TextField(blank=True, null=True)),
                ("txt_record", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "domains",
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="domains_organiz_5236ae_idx",
                    ),
                    models.Index(fields=["domain"], name="domains_domain_3bdc34_idx"),
                    models.Index(fields=["status"], name="domains_status_61b3bc_idx"),
                    models.Index(
                        fields=["verified_at"], name="domains_verifie_fb06c0_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="domains_created_9089ca_idx"
                    ),
                ],
            },
        ),
    ]
