# Generated by Django 5.2.6 on 2025-09-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='replit_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('send', 'Send'), ('open', 'Open'), ('click', 'Click'), ('bounce', 'Bounce'), ('unsubscribe', 'Unsubscribe'), ('spam_report', 'Spam Report')], max_length=50),
        ),
    ]
