# Generated by Django 5.2.6 on 2025-09-19 08:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_replit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('campaign_manager', 'Campaign Manager'), ('analyst', 'Analyst'), ('editor', 'Editor')], default='campaign_manager', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'email_otps',
                'indexes': [models.Index(fields=['email', 'is_verified'], name='email_otps_email_f84f45_idx'), models.Index(fields=['expires_at'], name='email_otps_expires_040e75_idx')],
            },
        ),
    ]
