# Generated by Django for subscription billing system

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone_alter_user_role_emailotp'),
    ]

    operations = [
        # Update subscription plan choices to include all billing options
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(
                choices=[
                    ('free_trial', 'Free Trial'),
                    ('basic_monthly', 'Basic Monthly'),
                    ('basic_yearly', 'Basic Yearly'),
                    ('pro_monthly', 'Pro Monthly'),
                    ('pro_yearly', 'Pro Yearly'),
                    ('premium_monthly', 'Premium Monthly'),
                    ('premium_yearly', 'Premium Yearly')
                ],
                default='free_trial',
                max_length=30
            ),
        ),
        # Add Stripe fields to Organization
        migrations.AddField(
            model_name='organization',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_subscription_active',
            field=models.BooleanField(default=True),
        ),
        # Add Stripe customer ID to User
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]