# Generated by Django 5.2.6 on 2025-09-22 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_is_staff_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('basic_monthly', 'Basic Monthly'), ('basic_yearly', 'Basic Yearly'), ('pro_monthly', 'Pro Monthly'), ('pro_yearly', 'Pro Yearly'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], max_length=30, unique=True)),
                ('price_cents', models.IntegerField()),
                ('contacts_limit', models.IntegerField()),
                ('campaigns_limit', models.IntegerField()),
                ('emails_per_month', models.IntegerField()),
                ('has_email_campaigns', models.BooleanField(default=True)),
                ('has_basic_analytics', models.BooleanField(default=True)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_ab_testing', models.BooleanField(default=False)),
                ('has_automation', models.BooleanField(default=False)),
                ('has_custom_templates', models.BooleanField(default=False)),
                ('has_white_labeling', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Features',
                'verbose_name_plural': 'Plan Features',
                'db_table': 'plan_features',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='emails_per_month_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='trialing', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=50)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.organization')),
            ],
            options={
                'db_table': 'payment_methods',
                'indexes': [models.Index(fields=['organization', 'is_default'], name='payment_met_organiz_cac888_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('basic_monthly', 'Basic Monthly'), ('basic_yearly', 'Basic Yearly'), ('pro_monthly', 'Pro Monthly'), ('pro_yearly', 'Pro Yearly'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], max_length=30)),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('canceled', 'Canceled'), ('renewed', 'Renewed'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('plan_changed', 'Plan Changed')], max_length=30)),
                ('amount_cents', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='core.organization')),
            ],
            options={
                'db_table': 'subscription_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='subscriptio_organiz_0fcdb0_idx'), models.Index(fields=['event_type', 'created_at'], name='subscriptio_event_t_5fbe7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNotification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('trial_ending', 'Trial Ending'), ('trial_ended', 'Trial Ended'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_canceled', 'Subscription Canceled'), ('payment_failed', 'Payment Failed'), ('payment_succeeded', 'Payment Succeeded'), ('limit_warning', 'Limit Warning'), ('limit_reached', 'Limit Reached')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_notifications', to='core.organization')),
            ],
            options={
                'db_table': 'subscription_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'notification_type', '-created_at'], name='subscriptio_organiz_e0c7a2_idx'), models.Index(fields=['status', 'channel'], name='subscriptio_status_f96653_idx')],
            },
        ),
    ]
