# Generated by Django 5.2.6 on 2025-09-22 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_populate_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
