# Generated by Django 5.2.6 on 2025-09-22 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('campaigns_created', models.IntegerField(default=0)),
                ('contacts_imported', models.IntegerField(default=0)),
                ('templates_created', models.IntegerField(default=0)),
                ('domains_verified', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('ab_tests_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='core.organization')),
            ],
            options={
                'db_table': 'usage_tracking',
                'indexes': [models.Index(fields=['organization', 'month'], name='usage_track_organiz_c28341_idx')],
                'unique_together': {('organization', 'month')},
            },
        ),
    ]
