# Generated by Django 5.2.6 on 2025-09-22 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_campaign_created_by_usagetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionnotification',
            name='delivery_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriptionnotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='subscriptio_user_id_2956df_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionnotification',
            index=models.Index(fields=['organization', 'is_read'], name='subscriptio_organiz_4e1835_idx'),
        ),
    ]
