# Generated by Django 5.2.6 on 2025-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subscriptionnotification_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
