# Generated by Django 5.2.6 on 2025-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='payment_method_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='payment_method_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
