# Generated by Django 5.2.6 on 2025-09-22 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subscriptionhistory_invoice_pdf_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'processed_webhook_events',
                'indexes': [models.Index(fields=['event_id'], name='processed_w_event_i_c57493_idx'), models.Index(fields=['processed_at'], name='processed_w_process_ba066e_idx'), models.Index(fields=['status'], name='processed_w_status_d7c8a3_idx')],
            },
        ),
    ]
