# Generated by Django 5.2.6 on 2025-09-23 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_processed_webhook_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=50)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.organization')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['organization', 'is_default'], name='cards_organiz_0e1a67_idx'),
        ),
    ]
