# Generated by Django 5.2.6 on 2025-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_card_delete_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='stripe_payment_method_id',
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(default='Card Holder', max_length=255),
        ),
    ]
