# Generated by Django 5.2.6 on 2025-09-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_stripe_add_cardholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.contactgroup'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.domain'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.emailtemplate'),
        ),
    ]
