# Generated by Django 5.2.6 on 2025-09-26 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_campaign_contact_group_campaign_domain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('campaign_manager', 'Campaign Manager'), ('analyst', 'Analyst'), ('editor', 'Editor')], default='campaign_manager', max_length=20)),
                ('token', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
            options={
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['email'], name='invitations_email_6e7169_idx'), models.Index(fields=['status'], name='invitations_status_1739b8_idx'), models.Index(fields=['expires_at'], name='invitations_expires_7f52c2_idx')],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
