# Generated by Django 5.2.6 on 2025-09-29 06:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_emailtemplate_options_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=core.models.generate_invitation_token, max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'email', 'status'], name='invitations_organiz_ccfe93_idx'),
        ),
    ]
