# Generated by Django 5.2.6 on 2025-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_invitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
