# Generated by Django 5.2.6 on 2025-09-29 07:58

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_invitation_token_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=core.models.generate_invitation_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionnotification',
            name='notification_type',
            field=models.CharField(choices=[('trial_ending', 'Trial Ending'), ('trial_ended', 'Trial Ended'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_canceled', 'Subscription Canceled'), ('payment_failed', 'Payment Failed'), ('payment_succeeded', 'Payment Succeeded'), ('limit_warning', 'Limit Warning'), ('limit_reached', 'Limit Reached'), ('team_invitation_received', 'Team Invitation Received'), ('team_invitation_accepted', 'Team Invitation Accepted')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('campaign_manager', 'Campaign Manager'), ('analyst', 'Analyst'), ('editor', 'Editor')], default='campaign_manager', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_memberships',
                'indexes': [models.Index(fields=['user', 'status'], name='organizatio_user_id_d04e52_idx'), models.Index(fields=['organization', 'status'], name='organizatio_organiz_33b363_idx'), models.Index(fields=['role'], name='organizatio_role_e3a08a_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
