# Generated by Django 5.2.6 on 2025-09-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_invitation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='credential_password_hash',
            field=models.CharField(blank=True, help_text='Password hash for this organization', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='credential_username',
            field=models.CharField(blank=True, help_text='Username for this organization (isolated per org)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='requires_password_change',
            field=models.BooleanField(default=True, help_text='Forces password change on next login'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'credential_username'], name='organizatio_organiz_d1927d_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'credential_username'), name='unique_org_username'),
        ),
    ]
