# Generated by Django 5.2.6 on 2025-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_populate_org_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='credential_username',
            field=models.CharField(blank=True, help_text='Proposed username for this organization', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='proposed_password_hash',
            field=models.CharField(blank=True, help_text='Optional initial password hash set by inviter', max_length=128, null=True),
        ),
    ]
